-- SIROS/ANAC v2 — esquema idempotente para Supabase/PostgreSQL

create table if not exists public.aeroportos (
  id bigint generated by default as identity primary key,
  icao text not null,
  iata text,
  nome text not null,
  cidade text not null,
  estado text not null,
  lat double precision,
  lon double precision
);

create table if not exists public.voos (
  id bigint generated by default as identity primary key,
  data_referencia date not null,
  icao_empresa text not null,
  nome_empresa text,
  numero_voo text not null,
  etapa text default '1',
  icao_origem text not null,
  icao_destino text not null,
  hr_partida_utc time,
  hr_chegada_utc time,
  partida_iso timestamptz,
  chegada_iso timestamptz,
  equipamento text,
  assentos integer,
  tipo_operacao text,
  tipo_servico text,
  criado_em timestamptz not null default now()
);

create table if not exists public.execucoes (
  id bigint generated by default as identity primary key,
  iniciado_em timestamptz not null default now(),
  concluido_em timestamptz,
  aeroportos_buscados text[],
  voos_processados integer default 0,
  lotes_enviados integer default 0,
  erros integer default 0,
  status text,
  observacao text
);

create table if not exists public.historico_vra (
  id bigint generated by default as identity primary key,
  ano_mes text not null,
  icao_empresa text not null,
  nr_voo text not null,
  icao_origem text,
  icao_destino text,
  dt_referencia date,
  partida_real timestamptz,
  chegada_real timestamptz,
  atraso_partida integer,
  atraso_chegada integer,
  situacao text,
  motivo_alteracao text,
  importado_em timestamptz not null default now()
);

-- Compatibilidade com instalações anteriores da atividade.
alter table public.execucoes add column if not exists aeroportos_buscados text[];
alter table public.execucoes add column if not exists voos_processados integer default 0;
alter table public.execucoes add column if not exists lotes_enviados integer default 0;
alter table public.execucoes add column if not exists erros integer default 0;
alter table public.execucoes add column if not exists status text;
alter table public.execucoes add column if not exists observacao text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'aeroportos_icao_key') then
    alter table public.aeroportos add constraint aeroportos_icao_key unique (icao);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'voos_unique') then
    alter table public.voos add constraint voos_unique
      unique (data_referencia, icao_empresa, numero_voo, icao_origem, icao_destino, etapa);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'historico_vra_unique') then
    alter table public.historico_vra add constraint historico_vra_unique
      unique (ano_mes, icao_empresa, nr_voo, icao_origem, icao_destino, dt_referencia);
  end if;
end $$;

create index if not exists voos_destino_data_idx
  on public.voos (icao_destino, data_referencia, chegada_iso);
create index if not exists voos_origem_data_idx
  on public.voos (icao_origem, data_referencia, partida_iso);
create index if not exists historico_vra_periodo_origem_idx
  on public.historico_vra (ano_mes, icao_origem, dt_referencia);
create index if not exists historico_vra_periodo_destino_idx
  on public.historico_vra (ano_mes, icao_destino, dt_referencia);
create index if not exists execucoes_concluido_idx
  on public.execucoes (concluido_em desc);

create or replace view public.voos_completo
with (security_invoker = true) as
select
  v.*,
  origem.nome as nome_aeroporto_origem,
  destino.nome as nome_aeroporto_destino
from public.voos v
left join public.aeroportos origem on origem.icao = v.icao_origem
left join public.aeroportos destino on destino.icao = v.icao_destino;

alter table public.aeroportos enable row level security;
alter table public.voos enable row level security;
alter table public.execucoes enable row level security;
alter table public.historico_vra enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='aeroportos' and policyname='leitura publica aeroportos') then
    create policy "leitura publica aeroportos" on public.aeroportos for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='voos' and policyname='leitura publica voos') then
    create policy "leitura publica voos" on public.voos for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='execucoes' and policyname='leitura publica execucoes') then
    create policy "leitura publica execucoes" on public.execucoes for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='historico_vra' and policyname='leitura publica historico_vra') then
    create policy "leitura publica historico_vra" on public.historico_vra for select using (true);
  end if;
end $$;

grant usage on schema public to anon, authenticated;
grant select on public.aeroportos, public.voos, public.execucoes, public.historico_vra, public.voos_completo to anon, authenticated;
grant all on public.aeroportos, public.voos, public.execucoes, public.historico_vra to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Os 41 aeroportos são carregados abaixo. O upsert torna o script repetível.

insert into public.aeroportos (icao, nome, cidade, estado) values
  ('SBRB', 'Rio Branco International', 'Rio Branco', 'Acre'),
  ('SBMO', 'Zumbi dos Palmares International', 'Maceió', 'Alagoas'),
  ('SBMQ', 'Alberto Alcolumbre International', 'Macapá', 'Amapá'),
  ('SBEG', 'Eduardo Gomes International', 'Manaus', 'Amazonas'),
  ('SBSV', 'Dep. Luís Eduardo Magalhães International', 'Salvador', 'Bahia'),
  ('SBIL', 'Jorge Amado', 'Ilhéus', 'Bahia'),
  ('SBPS', 'Porto Seguro International', 'Porto Seguro', 'Bahia'),
  ('SBFE', 'Félix Pereira de Magalhães', 'Feira de Santana', 'Bahia'),
  ('SBFZ', 'Pinto Martins International', 'Fortaleza', 'Ceará'),
  ('SBJU', 'Orlando Bezerra de Menezes', 'Juazeiro do Norte', 'Ceará'),
  ('SBBR', 'Pres. Juscelino Kubitschek International', 'Brasília', 'Distrito Federal'),
  ('SBVT', 'Eurico de Aguiar Salles', 'Vitória', 'Espírito Santo'),
  ('SBGO', 'Santa Genoveva', 'Goiânia', 'Goiás'),
  ('SWNR', 'Rio Verde', 'Rio Verde', 'Goiás'),
  ('SBSL', 'Cunha Machado International', 'São Luís', 'Maranhão'),
  ('SBIM', 'Prefeito Renato Moreira', 'Imperatriz', 'Maranhão'),
  ('SBCY', 'Marechal Rondon International', 'Cuiabá', 'Mato Grosso'),
  ('SBCG', 'Antonio João International', 'Campo Grande', 'Mato Grosso do Sul'),
  ('SBPP', 'Ponta Porã International', 'Ponta Porã', 'Mato Grosso do Sul'),
  ('SBCF', 'Tancredo Neves International', 'Belo Horizonte', 'Minas Gerais'),
  ('SBBH', 'Carlos Drummond de Andrade (Pampulha)', 'Belo Horizonte', 'Minas Gerais'),
  ('SBUL', 'Ten. Cel. Aviador César Bombonato', 'Uberlândia', 'Minas Gerais'),
  ('SBUR', 'Mário de Almeida Franco', 'Uberaba', 'Minas Gerais'),
  ('SBMK', 'Mario Ribeiro', 'Montes Claros', 'Minas Gerais'),
  ('SBIP', 'Usiminas', 'Ipatinga', 'Minas Gerais'),
  ('SBVG', 'Major Brig. Trompowsky', 'Varginha', 'Minas Gerais'),
  ('SBGV', 'Cel. Altino Machado de Oliveira', 'Governador Valadares', 'Minas Gerais'),
  ('SBBE', 'Val-de-Cans International', 'Belém', 'Pará'),
  ('SBSN', 'Maestro Wilson Fonseca', 'Santarém', 'Pará'),
  ('SBMA', 'João Corrêa da Rocha', 'Marabá', 'Pará'),
  ('SBJP', 'Presidente Castro Pinto', 'João Pessoa', 'Paraíba'),
  ('SBCT', 'Afonso Pena International', 'Curitiba', 'Paraná'),
  ('SBFI', 'Cataratas International', 'Foz do Iguaçu', 'Paraná'),
  ('SBCA', 'Aeroporto Regional do Oeste', 'Cascavel', 'Paraná'),
  ('SBLO', 'General Leite de Castro', 'Londrina', 'Paraná'),
  ('SBMG', 'Silvio Name Júnior Regional', 'Maringá', 'Paraná'),
  ('SBRF', 'Guararapes International', 'Recife', 'Pernambuco'),
  ('SBPL', 'Senador Nilo Coelho', 'Petrolina', 'Pernambuco'),
  ('SBTE', 'Senador Petrônio Portella', 'Teresina', 'Piauí'),
  ('SBGL', 'Galeão Internacional', 'Rio de Janeiro', 'Rio de Janeiro'),
  ('SBRJ', 'Santos Dumont', 'Rio de Janeiro', 'Rio de Janeiro'),
  ('SBCB', 'Cabo Frio International', 'Cabo Frio', 'Rio de Janeiro'),
  ('SBSG', 'São Gonçalo do Amarante International', 'Natal', 'Rio Grande do Norte'),
  ('SBPA', 'Salgado Filho International', 'Porto Alegre', 'Rio Grande do Sul'),
  ('SBCX', 'Hugo Cantergiani Regional', 'Caxias do Sul', 'Rio Grande do Sul'),
  ('SBPK', 'João Simões Lopes Neto', 'Pelotas', 'Rio Grande do Sul'),
  ('SBUG', 'Rubem Berta International', 'Uruguaiana', 'Rio Grande do Sul'),
  ('SBPV', 'Gov. Jorge Teixeira de Oliveira', 'Porto Velho', 'Rondônia'),
  ('SBJI', 'Ji-Paraná', 'Ji-Paraná', 'Rondônia'),
  ('SBBV', 'Atlas Brasil Cantanhede International', 'Boa Vista', 'Roraima'),
  ('SBFL', 'Hercílio Luz International', 'Florianópolis', 'Santa Catarina'),
  ('SBJV', 'Lauro Carneiro de Loyola', 'Joinville', 'Santa Catarina'),
  ('SBNF', 'Ministro Victor Konder', 'Navegantes', 'Santa Catarina'),
  ('SBJA', 'Humberto Ghizzo Bortoluzzi', 'Jaguaruna', 'Santa Catarina'),
  ('SBGR', 'Guarulhos International', 'Guarulhos', 'São Paulo'),
  ('SBSP', 'Congonhas', 'São Paulo', 'São Paulo'),
  ('SBKP', 'Viracopos International', 'Campinas', 'São Paulo'),
  ('SBRP', 'Leite Lopes', 'Ribeirão Preto', 'São Paulo'),
  ('SBSJ', 'Prof. Urbano Ernesto Stumpf', 'São José dos Campos', 'São Paulo'),
  ('SBDN', 'Presidente Prudente', 'Presidente Prudente', 'São Paulo'),
  ('SBAQ', 'Bartolomeu de Gusmão', 'Araraquara', 'São Paulo'),
  ('SBML', 'Frank Miloye Milenkowichi', 'Marília', 'São Paulo'),
  ('SBAU', 'Dario Guarita', 'Araçatuba', 'São Paulo'),
  ('SBSE', 'Santa Maria', 'Aracaju', 'Sergipe'),
  ('SBPJ', 'Brigadeiro Lysias Rodrigues', 'Palmas', 'Tocantins')
on conflict (icao) do update set
  nome = excluded.nome, cidade = excluded.cidade, estado = excluded.estado;

